"use client";
import { useState } from "react";
import { useTranslations } from "next-intl";
import { Button } from "@/components/global/primitives/button";
import { PasswordInput } from "@/components/global/primitives/password-input";
import { useSecurity } from "@/providers/security/security-provider";
import { SecurityPage } from "./security-page";
function PasswordChangeForm(){const t=useTranslations("SecurityPassword");const {changePassword}=useSecurity();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMessage("");const data=new FormData(e.currentTarget);setBusy(true);try{await changePassword({current_password:String(data.get("current_password")),new_password:String(data.get("new_password")),confirm_password:String(data.get("confirm_password"))});e.currentTarget.reset();setMessage(t("success"))}catch(error){setMessage(error instanceof Error?error.message:t("failure"))}finally{setBusy(false)}}return <SecurityPage title={t("title")} description={t("description")}><form className="max-w-xl space-y-4 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit}><label className="block text-sm font-medium">{t("current")}<PasswordInput className="mt-2" hideLabel={t("hidePassword")} name="current_password" required showLabel={t("showPassword")}/></label><label className="block text-sm font-medium">{t("new")}<PasswordInput className="mt-2" hideLabel={t("hidePassword")} name="new_password" required showLabel={t("showPassword")}/></label><label className="block text-sm font-medium">{t("confirm")}<PasswordInput className="mt-2" hideLabel={t("hidePassword")} name="confirm_password" required showLabel={t("showPassword")}/></label>{message?<p className="text-sm" role="status">{message}</p>:null}<Button disabled={busy} type="submit">{busy?t("saving"):t("save")}</Button></form></SecurityPage>}
export {PasswordChangeForm};
