# Generated by Django 5.2.16 on 2026-08-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="template",
            field=models.CharField(
                choices=[
                    ("password_changed", "Password changed"),
                    ("session_revoked", "Session revoked"),
                    ("other_sessions_revoked", "Other sessions revoked"),
                    ("workspace_invitation", "Workspace invitation"),
                    ("workspace_access_request", "Workspace access request"),
                    ("workspace_access_decision", "Workspace access decision"),
                    ("business_control_request", "Business control request"),
                    ("business_control_decision", "Business control decision"),
                    ("system_announcement", "System announcement"),
                ],
                db_index=True,
                max_length=48,
            ),
        ),
    ]
