# Generated by Django 5.2.16

import common.database.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("sw", "Swahili")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "appearance",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                        ],
                        default="DD/MM/YYYY",
                        max_length=10,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[("12h", "12-hour"), ("24h", "24-hour")],
                        default="24h",
                        max_length=3,
                    ),
                ),
                ("reduced_motion", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_user_preferences",
                "ordering": ["-created_at"],
            },
        ),
    ]
