# Generated by Django 5.2.16 on 2026-08-13 18:08

import common.database.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0005_business_deletion_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("category", models.CharField(max_length=48)),
                ("description", models.CharField(max_length=160)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("incurred_at", models.DateTimeField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="workspaces.business",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "commerce_expenses",
                "ordering": ["-incurred_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("sku", models.CharField(blank=True, default="", max_length=64)),
                ("variant", models.CharField(blank=True, default="", max_length=120)),
                ("unit", models.CharField(default="item", max_length=32)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "low_stock_threshold",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "current_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="workspaces.business",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_products",
                "ordering": ["name", "variant", "id"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("receipt_number", models.CharField(max_length=40)),
                (
                    "sale_type",
                    models.CharField(
                        choices=[("retail", "Retail"), ("wholesale", "Wholesale")],
                        default="retail",
                        max_length=16,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cost_of_goods",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("partial", "Partial"),
                            ("unpaid", "Unpaid"),
                        ],
                        default="paid",
                        max_length=16,
                    ),
                ),
                ("sold_at", models.DateTimeField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="workspaces.business",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "commerce_sales",
                "ordering": ["-sold_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "cost_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "returned_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="commerce.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commerce.sale",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_sale_items",
            },
        ),
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("refund", "Refund"),
                            ("replacement", "Replacement"),
                            ("credit", "Store credit"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("reason", models.CharField(max_length=240)),
                ("returned_at", models.DateTimeField()),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="commerce.sale",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_returns",
                "ordering": ["-returned_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "condition",
                    models.CharField(
                        choices=[("sellable", "Sellable"), ("damaged", "Damaged")],
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "sale_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="commerce.saleitem",
                    ),
                ),
                (
                    "return_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commerce.salereturn",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_return_items",
            },
        ),
        migrations.CreateModel(
            name="StockBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "quantity_received",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "quantity_remaining",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "additional_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("received_at", models.DateTimeField()),
                (
                    "supplier_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_batches",
                        to="commerce.product",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_stock_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "commerce_stock_batches",
                "ordering": ["received_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "sale_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="commerce.saleitem",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_allocations",
                        to="commerce.stockbatch",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_sale_allocations",
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receipt", "Stock receipt"),
                            ("sale", "Sale"),
                            ("return", "Customer return"),
                            ("damage", "Damaged"),
                            ("loss", "Lost or stolen"),
                            ("expired", "Expired"),
                            ("correction", "Counting correction"),
                            ("internal_use", "Internal use"),
                            ("giveaway", "Giveaway"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "quantity_delta",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=240)),
                ("occurred_at", models.DateTimeField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements",
                        to="workspaces.business",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="commerce.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements",
                        to="commerce.sale",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="commerce.stockbatch",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_inventory_movements",
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("category", models.CharField(max_length=48)),
                ("month", models.DateField()),
                (
                    "planned_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="workspaces.business",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_budgets",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "category", "month"),
                        name="commerce_budget_period_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommerceDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("key", models.CharField(max_length=80)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("attention", "Attention"),
                            ("urgent", "Urgent"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("explanation", models.CharField(max_length=320)),
                (
                    "action_path",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commerce_decisions",
                        to="workspaces.business",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_decisions",
                "ordering": ["resolved_at", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "key"), name="commerce_decision_key_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku", ""), _negated=True),
                fields=("business", "sku"),
                name="commerce_business_sku_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("selling_price__gte", 0)),
                name="commerce_product_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_quantity__gte", 0)),
                name="commerce_product_stock_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                fields=("business", "receipt_number"), name="commerce_receipt_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_received__gt", 0)),
                name="commerce_batch_received_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_remaining__gte", 0)),
                name="commerce_batch_remaining_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)),
                name="commerce_batch_cost_nonnegative",
            ),
        ),
    ]
