# Generated by Django 5.2.16 on 2026-08-14 16:10

import common.database.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_availability(apps, schema_editor):
    Product = apps.get_model("commerce", "Product")
    StockBatch = apps.get_model("commerce", "StockBatch")
    StockReceipt = apps.get_model("commerce", "StockReceipt")

    for business_id in Product.objects.values_list("business_id", flat=True).distinct():
        used = set(
            Product.objects.filter(business_id=business_id)
            .exclude(sku="")
            .values_list("sku", flat=True)
        )
        number = 1
        for product in Product.objects.filter(business_id=business_id, sku="").order_by(
            "created_at", "id"
        ):
            while f"ITM-{number:06d}" in used:
                number += 1
            product.sku = f"ITM-{number:06d}"
            product.save(update_fields=["sku"])
            used.add(product.sku)
            number += 1

    sequences = {}
    for batch in (
        StockBatch.objects.select_related("product")
        .filter(receipt__isnull=True)
        .order_by("product__business_id", "received_at", "created_at", "id")
    ):
        business_id = batch.product.business_id
        sequences[business_id] = sequences.get(business_id, 0) + 1
        sequence = sequences[business_id]
        receipt = StockReceipt.objects.create(
            business_id=business_id,
            reference=f"MZIGO-{sequence:06d}",
            sequence=sequence,
            status="received",
            supplier_name=batch.supplier_name,
            supplier_reference=batch.reference,
            additional_cost=batch.additional_cost,
            received_at=batch.received_at,
            recorded_by_id=batch.recorded_by_id,
        )
        batch.receipt_id = receipt.id
        batch.received_unit = batch.product.unit
        batch.save(update_fields=["receipt", "received_unit"])


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0003_sale_lifecycle"),
        ("workspaces", "0005_business_deletion_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("reference", models.CharField(max_length=40)),
                ("sequence", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("received", "Received"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "supplier_reference",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "additional_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "commerce_stock_receipts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackedUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("internal_serial", models.CharField(max_length=40)),
                ("imei", models.CharField(blank=True, default="", max_length=80)),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("condition", models.CharField(blank=True, default="", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "commerce_tracked_units",
                "ordering": ["internal_serial"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="commerce_product_price_nonnegative",
        ),
        migrations.RemoveConstraint(
            model_name="stockbatch",
            name="commerce_batch_cost_nonnegative",
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="product",
            name="group",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="product",
            name="tracking_mode",
            field=models.CharField(
                choices=[("quantity", "Quantity"), ("individual", "Individual items")],
                default="quantity",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="conversion_to_base",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="received_unit",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode", ""), _negated=True),
                fields=("business", "barcode"),
                name="commerce_business_barcode_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("selling_price__isnull", True),
                    ("selling_price__gte", 0),
                    _connector="OR",
                ),
                name="commerce_product_price_nonnegative",
            ),
        ),
        migrations.AddField(
            model_name="stockreceipt",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_receipts",
                to="workspaces.business",
            ),
        ),
        migrations.AddField(
            model_name="stockreceipt",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recorded_stock_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="commerce.stockreceipt",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit_cost__isnull", True), ("unit_cost__gte", 0), _connector="OR"
                ),
                name="commerce_batch_cost_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("conversion_to_base__gt", 0)),
                name="commerce_batch_conversion_positive",
            ),
        ),
        migrations.AddField(
            model_name="trackedunit",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tracked_units",
                to="commerce.product",
            ),
        ),
        migrations.AddField(
            model_name="trackedunit",
            name="stock_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tracked_units",
                to="commerce.stockbatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreceipt",
            constraint=models.UniqueConstraint(
                fields=("business", "reference"),
                name="commerce_stock_receipt_reference_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreceipt",
            constraint=models.UniqueConstraint(
                fields=("business", "sequence"),
                name="commerce_stock_receipt_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("additional_cost__gte", 0)),
                name="commerce_stock_receipt_cost_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="trackedunit",
            constraint=models.UniqueConstraint(
                fields=("product", "internal_serial"),
                name="commerce_product_internal_serial_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="trackedunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("imei", ""), _negated=True),
                fields=("product", "imei"),
                name="commerce_product_imei_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="trackedunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("serial_number", ""), _negated=True),
                fields=("product", "serial_number"),
                name="commerce_product_serial_unique",
            ),
        ),
        migrations.RunPython(preserve_existing_availability, migrations.RunPython.noop),
    ]
