# Generated by Django 5.2.16 on 2026-08-14 20:07

import common.database.uuid
import django.db.models.deletion
from django.db import migrations, models


def preserve_existing_stock_lines(apps, schema_editor):
    StockBatch = apps.get_model("commerce", "StockBatch")
    StockContainer = apps.get_model("commerce", "StockContainer")
    StockGroup = apps.get_model("commerce", "StockGroup")

    containers = {}
    names = {}
    for line in StockBatch.objects.select_related("product", "receipt").filter(
        receipt__isnull=False, stock_group__isnull=True
    ):
        receipt_id = line.receipt_id
        if receipt_id not in containers:
            containers[receipt_id] = StockContainer.objects.create(
                receipt_id=receipt_id, name="Imported stock", position=0
            )
            names[receipt_id] = set()
        base_name = line.product.group or line.product.name
        name = base_name
        suffix = 2
        while name in names[receipt_id]:
            name = f"{base_name} {suffix}"
            suffix += 1
        names[receipt_id].add(name)
        group = StockGroup.objects.create(
            batch=containers[receipt_id],
            name=name,
            quantity=line.quantity_received,
            unit=line.product.unit,
            buying_price=line.unit_cost,
            selling_price=line.product.selling_price,
            position=len(names[receipt_id]) - 1,
        )
        line.stock_group_id = group.id
        line.save(update_fields=["stock_group"])


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0004_stockreceipt_trackedunit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockContainer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("notes", models.CharField(blank=True, default="", max_length=240)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="commerce.stockreceipt",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_stock_containers",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("unit", models.CharField(max_length=32)),
                ("base_unit", models.CharField(blank=True, default="", max_length=32)),
                (
                    "conversion_to_base",
                    models.DecimalField(decimal_places=6, default=1, max_digits=14),
                ),
                (
                    "buying_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="commerce.stockcontainer",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_stock_groups",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="stock_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="type_lines",
                to="commerce.stockgroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcontainer",
            constraint=models.UniqueConstraint(
                fields=("receipt", "name"), name="commerce_receipt_batch_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockgroup",
            constraint=models.UniqueConstraint(
                fields=("batch", "name"), name="commerce_batch_group_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="commerce_stock_group_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("conversion_to_base__gt", 0)),
                name="commerce_stock_group_conversion_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("buying_price__isnull", True),
                    ("buying_price__gte", 0),
                    _connector="OR",
                ),
                name="commerce_stock_group_buying_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("selling_price__isnull", True),
                    ("selling_price__gte", 0),
                    _connector="OR",
                ),
                name="commerce_stock_group_selling_price_nonnegative",
            ),
        ),
        migrations.RunPython(preserve_existing_stock_lines, migrations.RunPython.noop),
    ]
