# Generated by Django 5.2.16 on 2026-08-14 21:29

import common.database.uuid
import django.db.models.deletion
from django.db import migrations, models


def preserve_existing_stock_codes_and_identifiers(apps, schema_editor):
    StockContainer = apps.get_model("commerce", "StockContainer")
    StockGroup = apps.get_model("commerce", "StockGroup")
    TrackedUnit = apps.get_model("commerce", "TrackedUnit")
    TrackedUnitIdentifier = apps.get_model("commerce", "TrackedUnitIdentifier")

    receipt_ids = StockContainer.objects.values_list("receipt_id", flat=True).distinct()
    for receipt_id in receipt_ids.iterator():
        batches = StockContainer.objects.filter(receipt_id=receipt_id).order_by(
            "position", "created_at"
        )
        for position, batch in enumerate(batches, start=1):
            batch.code = f"BAT-{position:03d}"
            batch.save(update_fields=["code"])
            groups = StockGroup.objects.filter(batch_id=batch.id).order_by(
                "position", "created_at"
            )
            for group_position, group in enumerate(groups, start=1):
                group.code = f"GRP-{group_position:03d}"
                group.save(update_fields=["code"])

    identifier_rows = []
    for unit in TrackedUnit.objects.all().iterator():
        if unit.imei:
            identifier_rows.append(
                TrackedUnitIdentifier(unit_id=unit.id, kind="imei", value=unit.imei)
            )
        if unit.serial_number:
            identifier_rows.append(
                TrackedUnitIdentifier(
                    unit_id=unit.id, kind="serial", value=unit.serial_number
                )
            )
    TrackedUnitIdentifier.objects.bulk_create(identifier_rows)


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0005_stockcontainer_stockgroup_stockbatch_stock_group_and_more"),
        ("workspaces", "0005_business_deletion_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedUnitIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("imei", "IMEI"),
                            ("serial", "Serial number"),
                            ("chassis", "Chassis or VIN"),
                            ("barcode", "Barcode"),
                            ("engine", "Engine number"),
                            ("registration", "Registration number"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=160)),
            ],
            options={
                "db_table": "commerce_tracked_unit_identifiers",
            },
        ),
        migrations.CreateModel(
            name="UnitDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=32)),
                ("base_unit", models.CharField(blank=True, default="", max_length=32)),
                (
                    "conversion_to_base",
                    models.DecimalField(decimal_places=6, default=1, max_digits=14),
                ),
            ],
            options={
                "db_table": "commerce_unit_definitions",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="stockcontainer",
            name="code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="stockgroup",
            name="code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="trackedunit",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="trackedunit",
            name="capacity",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="trackedunit",
            name="color",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="trackedunit",
            name="model_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddConstraint(
            model_name="stockcontainer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("receipt", "code"),
                name="commerce_receipt_batch_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockgroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("batch", "code"),
                name="commerce_batch_group_code_unique",
            ),
        ),
        migrations.AddField(
            model_name="trackedunitidentifier",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identifiers",
                to="commerce.trackedunit",
            ),
        ),
        migrations.AddField(
            model_name="unitdefinition",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commerce_units",
                to="workspaces.business",
            ),
        ),
        migrations.RunPython(
            preserve_existing_stock_codes_and_identifiers,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="trackedunitidentifier",
            constraint=models.UniqueConstraint(
                fields=("unit", "kind", "value"), name="commerce_unit_identifier_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitdefinition",
            constraint=models.UniqueConstraint(
                fields=("business", "code"), name="commerce_business_unit_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitdefinition",
            constraint=models.UniqueConstraint(
                fields=("business", "name"), name="commerce_business_unit_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("conversion_to_base__gt", 0)),
                name="commerce_unit_conversion_positive",
            ),
        ),
    ]
