# Generated by Django 5.2.16 on 2026-08-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0006_trackedunitidentifier_unitdefinition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockbatch",
            name="tracking_mode",
            field=models.CharField(
                choices=[("quantity", "Quantity"), ("individual", "Individual items")],
                default="quantity",
                max_length=16,
            ),
        ),
    ]
