# Generated by Django 5.2.16 on 2026-08-15 11:16

import common.database.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_stock_expenses(apps, schema_editor):
    Expense = apps.get_model("commerce", "Expense")
    StockReceipt = apps.get_model("commerce", "StockReceipt")
    for receipt in StockReceipt.objects.filter(
        status="received", additional_cost__gt=0
    ).iterator():
        Expense.objects.get_or_create(
            stock_receipt_id=receipt.id,
            defaults={
                "business_id": receipt.business_id,
                "category": "stock_expense",
                "description": f"Stock expenses for {receipt.reference}",
                "amount": receipt.additional_cost,
                "incurred_at": receipt.received_at or receipt.created_at,
                "recorded_by_id": receipt.recorded_by_id,
            },
        )


def remove_backfilled_stock_expenses(apps, schema_editor):
    Expense = apps.get_model("commerce", "Expense")
    Expense.objects.filter(stock_receipt__isnull=False).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0007_stockbatch_tracking_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="stock_receipt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_expense",
                to="commerce.stockreceipt",
            ),
        ),
        migrations.AddField(
            model_name="stockreceipt",
            name="parent_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="late_deliveries",
                to="commerce.stockreceipt",
            ),
        ),
        migrations.CreateModel(
            name="StockReceiptAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.database.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("edit_details", "Edit details"),
                            ("late_delivery", "Late delivery"),
                        ],
                        max_length=24,
                    ),
                ),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="commerce.stockreceipt",
                    ),
                ),
            ],
            options={
                "db_table": "commerce_stock_receipt_audit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(
            backfill_stock_expenses,
            remove_backfilled_stock_expenses,
        ),
    ]
