# Generated by Django 5.2.3 on 2025-07-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
