# Generated by Django 5.2.3 on 2025-07-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comparison_products',
            field=models.ManyToManyField(blank=True, related_name='compared_with', to='store.product'),
        ),
    ]
