# Generated by Django 5.2.16 on 2026-07-25 19:53

import common.database.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=common.database.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('registration', 'Registration')], default='registration', max_length=32)),
                ('code_digest', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_email_verification_challenges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'consumed_at'], name='identity_email_challenge_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts'))), name='identity_email_attempt_limit')],
            },
        ),
    ]
