# Generated by Django 5.2.16 on 2026-07-28 13:59

import common.database.uuid
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_emailverificationchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=common.database.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('family_id', models.UUIDField(db_index=True, default=common.database.uuid.generate_uuid, editable=False)),
                ('current_refresh_jti', models.UUIDField(blank=True, null=True, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, choices=[('logout', 'Logout'), ('logout_all', 'Logout all'), ('refresh_reuse', 'Refresh token reuse'), ('user_inactive', 'User inactive'), ('expired', 'Expired'), ('security_event', 'Security event')], default='', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_user_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at', 'expires_at'], name='identity_session_active_idx')],
            },
        ),
    ]
