# Generated by Django 5.2.16 on 2026-07-28 15:37

import common.database.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentitySecurityEvent',
            fields=[
                ('id', models.UUIDField(default=common.database.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('email_challenge_issued', 'Email challenge issued'), ('email_delivery_succeeded', 'Email delivery succeeded'), ('email_delivery_failed', 'Email delivery failed'), ('email_verification_succeeded', 'Email verification succeeded'), ('email_verification_failed', 'Email verification failed'), ('email_resend_blocked', 'Email resend blocked')], db_index=True, max_length=64)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('blocked', 'Blocked')], db_index=True, max_length=16)),
                ('challenge_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_hash', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_security_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='identity_security_event_idx')],
            },
        ),
    ]
